# Generated by Django 4.2.7 on 2023-12-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='patiant_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patiant_phone',
            new_name='patient_phone',
        ),
    ]
