# Generated by Django 4.2.7 on 2023-12-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_rename_patiant_name_booking_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='Booked_On',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='Booking_Date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='Doctor_Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patiant_email',
            new_name='Patient_Email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_name',
            new_name='Patient_Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_phone',
            new_name='Patient_Phone',
        ),
    ]
